language: go
go:
- 1.12.x
- master
go_import_path: github.com/dotslash/bookmarks
env:
  - GO111MODULE=on
script:
  - go build
  - go test -race -coverprofile=coverage.txt -covermode=atomic github.com/dotslash/bookmarks/internal
after_success:
  - bash <(curl -s https://codecov.io/bash)